# Generated by Django 5.2.8 on 2026-07-13 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PB_Assistant', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='academicpaper',
            name='all_pdf_urls',
            field=models.JSONField(blank=True, default=list, help_text='A JSON array of URLs'),
        ),
        migrations.AddField(
            model_name='academicpaper',
            name='best_oa_pdf_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='academicpaper',
            name='openalex_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicpaper',
            name='scopus_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='academicpaper',
            name='wos_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='BoundaryQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('planetary_boundary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queries', to='PB_Assistant.planetaryboundary')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_queries', to='PB_Assistant.source')),
            ],
            options={
                'unique_together': {('planetary_boundary', 'source')},
            },
        ),
    ]
